version : "2"
services:
    web:
        build: .
        volumes:
            - .:/code
        ports:
            - "5000:5000"
        links:
            - db
    db:
        image: mysql:5.5.52
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=pollution_monitoring
            - MYSQL_USER=pollution
            - MYSQL_PASSWORD=pollution

