version : "2"
services:
    web:
        build: .
        volumes:
            - .:/code
        environment:
            - ENVIRONMENT=dev
        ports:
            - "5000:5000"
        links:
            - db
    db:
        image: mysql:5.5.52
        environment:
            - MYSQL_ROOT_PASSWORD=pollution
            - MYSQL_DATABASE=pollution_monitoring
            - MYSQL_USER=pollution
            - MYSQL_PASSWORD=pollution
        ports:
            - "3306:3306"

