version : "2"
services:
    web:
        build: .
        volumes:
            - .:/code
        ports:
            - "5000:5000"
        depends_on:
            - db
    db:
        image: mysql:5.5.52
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes

